version: '3.9'

services:
  iotbay-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=A(!)TerriblePassw0rd1
    ports:
      - 1433:1433
  iotbay-app:
    image: ${DOCKER_REGISTRY-}iotbay
    build:
      context: src/IoTBay
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
    depends_on:
      - iotbay-db