version: '3.9'

services:
  iotbay-app:
    image: ${DOCKER_REGISTRY-}iotbay
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
      - 4433:443
